import { useEffect, useRef, useState } from 'react';
import type { CalculationSettings, Recommendation } from '../shared/types';
import { Badge, Icon, number, date, Toggle, unitLabel } from '../shared/ui';
import { LineChart, SeasonChart } from '../shared/ui/Charts';

export default function ProductPage({ item, onClose, previousQty, settings, onScenario, busy, calculating, onCreateOrder }: {
  item: Recommendation; onClose: () => void; previousQty?: number; settings: CalculationSettings;
  onScenario: (s: CalculationSettings) => void; busy: boolean; calculating: boolean; onCreateOrder: () => void;
}) {
  const [tab, setTab] = useState<'explanation' | 'history' | 'scenario'>('explanation');
  const [scenario, setScenario] = useState(settings);
  const closeRef = useRef<HTMLButtonElement>(null);
  const dialogRef = useRef<HTMLElement>(null);
  useEffect(() => {
    const prior = document.activeElement as HTMLElement | null;
    closeRef.current?.focus(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden';
    const listener = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'Tab') {
        const nodes = dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), a[href], select:not(:disabled)');
        if (!nodes?.length) return;
        const first = nodes[0]; const last = nodes[nodes.length - 1];
        if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    };
    document.addEventListener('keydown', listener);
    return () => { document.body.style.overflow = old; document.removeEventListener('keydown', listener); prior?.focus(); };
  }, []);
  const correction = (key: 'use_outliers' | 'use_stockout' | 'use_seasonality' | 'use_trend', value: boolean) => setScenario({ ...scenario, [key]: value });
  return <div className="drawer-overlay" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section className="product-drawer" role="dialog" aria-modal="true" aria-labelledby="product-title" ref={dialogRef}>
    <header className="drawer-header"><div className="section-kicker">КАРТОЧКА РЕКОМЕНДАЦИИ</div><button className="icon-button close-drawer" ref={closeRef} onClick={onClose} aria-label="Закрыть карточку"><Icon name="close" size={22}/></button><h2 id="product-title">{item.name}</h2><div className="drawer-meta"><span className="sku">{item.sku}</span><span>{item.warehouse_id}</span><span>{item.supplier_name}</span><Badge urgency={item.urgency}/></div></header>
    <div className="drawer-tabs">{([['explanation', 'Обоснование'], ['history', 'Данные и события'], ['scenario', 'Что, если?']] as const).map(([key, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{key === 'scenario' && <Icon name="spark" size={16}/>} {label}</button>)}</div>
    <div className="drawer-body">
      <div className="quantity-hero"><div><span>{calculating ? 'ПРЕДЫДУЩАЯ РЕКОМЕНДАЦИЯ' : 'РЕКОМЕНДУЕМ ЗАКАЗАТЬ'}</span><strong>{number(item.recommended_qty_exact ?? item.recommended_qty, 12)} <small>{unitLabel(item.unit)}</small></strong><p>Покрытие на {item.horizon_days} дней · доставка {item.lead_time_days} дней</p></div><span className="quantity-hero-icon"><Icon name="box" size={42}/></span></div>
      {(previousQty !== undefined || calculating) && <div className="comparison-notice" role="status" aria-live="polite">{calculating ? <span className="spinner"/> : <Icon name="spark" size={20}/>}<div>{calculating ? <><strong>Сценарий рассчитывается…</strong><p>Предыдущее количество: {number(previousQty ?? item.recommended_qty_exact ?? item.recommended_qty, 12)} {unitLabel(item.unit)}. Новый результат появится после завершения расчёта.</p></> : <><strong>Сравнение сценария: {number(previousQty, 12)} → {number(item.recommended_qty_exact ?? item.recommended_qty, 12)} {unitLabel(item.unit)}</strong><p>{Number(item.recommended_qty) === previousQty ? 'Выбранные поправки не изменили итоговое количество.' : 'Количество пересчитано с выбранными поправками. Это модельный сценарий.'}</p></>}</div></div>}
      {tab === 'explanation' && <>
        <section className="drawer-section"><h3>Как получилось это количество</h3><p className="section-description">Прозрачный баланс потребности и доступного запаса.</p><div className="formula-grid"><div><span>Прогноз спроса</span><strong>{number(item.forecast_demand, 2)}</strong></div><span className="formula-operator">+</span><div><span>Страховой запас</span><strong>{number(item.safety_stock, 2)}</strong></div><span className="formula-operator">−</span><div><span>Доступно</span><strong>{number(item.available_stock, 12)}</strong></div><span className="formula-operator">−</span><div><span>В пути вовремя</span><strong>{number(item.inbound_qty, 12)}</strong></div></div>{item.balance_requirement !== undefined && <div className="formula-result"><span>Баланс потребности, минимум 0</span><strong>{number(item.balance_requirement, 2)} {unitLabel(item.unit)}</strong></div>}{item.timing_adjustment !== undefined && Math.abs(item.timing_adjustment) > 0.001 && <div className="formula-result muted"><span>Поправка по датам поступления</span><strong>{item.timing_adjustment > 0 ? "+" : ""}{number(item.timing_adjustment, 2)} {unitLabel(item.unit)}</strong></div>}<div className="formula-result"><span>Потребность после проверки дат поставок</span><strong>{number(item.raw_requirement, 2)} {unitLabel(item.unit)}</strong></div><div className="formula-result muted"><span>Округление и условия поставщика</span><strong>{Number(item.rounding_adjustment) > 0 ? '+' : ''}{number(item.rounding_adjustment, 2)} {unitLabel(item.unit)}</strong></div><div className="reason-card"><Icon name="info" size={20}/><p>{item.explanation.replace(/\bpcs\b/g, "шт.")}</p></div></section>
        <section className="drawer-section"><h3>Что учтено в прогнозе</h3><div className="factor-grid"><div><span>Базовый спрос</span><strong>{number(item.base_daily_demand, 2)} <small>{unitLabel(item.unit)}/день</small></strong></div><div><span>Сезонный коэффициент</span><strong>×{number(item.seasonality_factor, 2)}</strong></div><div><span>Тренд за 30 дней</span><strong>{Number(item.growth_pct) > 0 ? '+' : ''}{number(item.growth_pct, 2)}%</strong></div><div><span>Оценка упущенного спроса</span><strong>{number(item.estimated_lost_demand, 2)} <small>{unitLabel(item.unit)}</small></strong></div></div></section>
        <section className="drawer-section"><div className="section-heading-inline"><h3>Остаток в будущем</h3><span className="period-badge">{item.horizon_days} дней</span></div><LineChart data={(item.projection || []).map(x => ({ ...x }))} series={[{ key: 'stock_with_order', label: 'С рекомендованным заказом', color: '#287b60' }, { key: 'stock_without_order', label: 'Без нового заказа', color: '#bd826d', dashed: true }]} unit={unitLabel(item.unit)} ariaLabel="Прогноз остатка с заказом и без заказа"/>{item.shortage_date && <div className="notice warning"><Icon name="warning" size={18}/><span>Без нового заказа дефицит ожидается {date(item.shortage_date)}.{item.urgency === 'critical' ? ' Обычная поставка может не успеть: рассмотрите ускорение или перемещение.' : ''}</span></div>}</section>
        <section className="drawer-section"><h3>Условия поставки</h3><div className="supplier-facts"><div><span>Поставщик</span><strong>{item.supplier_name}</strong></div><div><span>Срок поставки</span><strong>{item.lead_time_days} дней</strong></div><div><span>Минимальная партия</span><strong>{number(item.moq, 12)} {unitLabel(item.unit)}</strong></div><div><span>Кратность</span><strong>{number(item.order_multiple, 12)} {unitLabel(item.unit)}</strong></div></div></section>
      </>}
      {tab === 'history' && <>
        <section className="drawer-section"><h3>Продажи и очищенный спрос</h3><p className="section-description">Месячные объёмы по всей доступной истории. Исходные продажи сохранены.</p><LineChart data={(item.chart || []).map(x => ({ ...x }))} series={[{ key: 'baseline', label: 'Очищенный спрос', color: '#287b60' }, { key: 'observed', label: 'Фактические продажи', color: '#abc252', dashed: true }]} ariaLabel="История фактических продаж и очищенного спроса" unit={unitLabel(item.unit)}/></section>
        <section className="drawer-section"><h3>Сезонный профиль</h3><p className="section-description">Коэффициент выше 1 означает спрос выше среднего уровня.</p><SeasonChart values={item.seasonality || []}/></section>
        <section className="drawer-section"><h3>Клиентские события <span className="count-label">{(item.events || []).length}</span></h3>{(item.events || []).length ? <div className="events-list">{item.events.map((event, i) => <div className="event-card" key={`${event.date}-${i}`}><div><span className={`event-dot ${event.excluded ? 'excluded' : ''}`}><Icon name={event.excluded ? 'shield' : 'check'} size={17}/></span><div><strong>{number(event.qty)} {unitLabel(item.unit)} · {date(event.date)}</strong><small>Клиент {event.customer}</small></div><span className={`event-tag ${event.excluded ? 'excluded' : ''}`}>{event.excluded ? 'Исключено' : 'Сохранено'}</span></div><p>{event.reason}</p></div>)}</div> : <p className="muted">Крупных клиентских событий не обнаружено.</p>}</section>
        <section className="drawer-section"><h3>Отсутствие товара</h3><div className="factor-grid"><div><span>Дней stockout</span><strong>{number(item.stockout_days, 0)}</strong></div><div><span>Оценённый упущенный спрос</span><strong>{number(item.estimated_lost_demand, 2)} <small>{unitLabel(item.unit)}</small></strong></div></div><p className="section-description">Оценка скрытого спроса повышает базовый уровень потребности. Исторические потерянные продажи не добавляются к заказу как долг.</p></section>
      </>}
      {tab === 'scenario' && <section className="drawer-section scenario-section"><div className="section-kicker">ЛАБОРАТОРИЯ РЕШЕНИЙ</div><h3>А если считать иначе?</h3><p>Отключите одну поправку и посмотрите, как изменится рекомендация. Будет создан новый расчёт для текущего склада и категории.</p><div className="scenario-toggles"><Toggle label="Восстановление спроса при stockout" hint="Учитывать спрос, скрытый отсутствием товара" checked={scenario.use_stockout} onChange={v => correction('use_stockout', v)} disabled={busy}/><Toggle label="Защита от разовых заказов" hint="Исключать разовые клиентские события из baseline" checked={scenario.use_outliers} onChange={v => correction('use_outliers', v)} disabled={busy}/><Toggle label="Сезонность" hint="Использовать календарный профиль спроса" checked={scenario.use_seasonality} onChange={v => correction('use_seasonality', v)} disabled={busy}/><Toggle label="Устойчивый тренд" hint="Учитывать рост или снижение спроса" checked={scenario.use_trend} onChange={v => correction('use_trend', v)} disabled={busy}/></div><button className="button primary scenario-run" disabled={busy} onClick={() => onScenario(scenario)}>{busy ? <span className="spinner small"/> : <Icon name="spark" size={18}/>}Пересчитать и сравнить</button><div className="notice neutral"><Icon name="info" size={18}/><span>Меняется текущий расчёт рекомендаций. Сохранённые и утверждённые заказы остаются самостоятельными снимками.</span></div></section>}
      {!!(item.data_warnings || []).length && <section className="drawer-section"><h3>Качество данных</h3><div className="quality-warnings">{item.data_warnings.map((warning, i) => <div key={i}><Icon name="info" size={16}/><span>{warning}</span></div>)}</div></section>}
    </div>
    <footer className="drawer-footer"><span><Icon name="shield" size={16}/>Решение принимает менеджер</span><button className="button primary" title="Создать черновик по всем позициям к заказу этого поставщика" onClick={onCreateOrder} disabled={busy || Number(item.recommended_qty) <= 0}><Icon name="orders" size={17}/>Заказ поставщику</button></footer>
  </section></div>;
}
